language:
    - objective-c

before_install:
  - brew update
  
  # Download and install Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-MacOSX-x86_64.sh -O miniconda.sh 
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - ls -al /Users/travis
  - export PATH=/Users/travis/miniconda/bin:$PATH
  
  # Update conda
  - conda update --yes conda
  - conda update --yes conda
  
    # install build tools
  - conda install --yes conda-build
  - conda install --yes binstar
    #- conda install --yes jinja2

  # debug
  - pwd

install:
  - cd recipes/trmm_rsl/

script: conda build .
  
after_success:
   
    #- binstar register --user master_builder --private /Users/travis/miniconda/conda-bld/osx-64/trmm_rsl-1.44-0.tar.bz2
    #- binstar upload --user master_builder /Users/travis/miniconda/conda-bld/osx-64/trmm_rsl-1.44-0.tar.bz2

deploy:
  provider: s3
  access_key_id: AKIAJXRRZXWB4MOZ5RZQ
  secret_access_key:
    secure: dR9IJRnfHbsU5uSJvHWGBG9mn/kLRIX3W8IIhWYuwORCt3MDcEYrRBUMbqfsABC3Yk/vqFLzZdj05SJc+0MISNSAtZJlhYL4ZbIaIY2KUB2rVfUamxmru+m23XtgW0vEEF5fjTzSgCnXvF3qg4tZ7lHpkOLpM96hS4ktYxbdH1E=
  bucket: masterbuildosx
  skip_cleanup: true
  local-dir: /Users/travis/miniconda/conda-bld/osx-64/
