language:
    - objective-c

env:
    global:
        - secure: "ixlGs/3Nd/+7M4TxOhhOHcdniIbUTgLodgM+SQGIEe8CtfgqIrtyBTdutys4lXR2R4ZyV1fGLz/lf4A9Zkk6skVEaHmgRwU23rClppLtEaHv6K4FMjjOV1eCEbDdYVcFZ0LGi9tP15AZ6/LtrG3tcxKAZeLB1U+Mx32h6pRdALw="

before_install:
  - brew update
  
  # Download and install Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-MacOSX-x86_64.sh -O miniconda.sh 
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - ls -al /Users/travis
  - export PATH=/Users/travis/miniconda/bin:$PATH
  
  # Update conda
  - conda update --yes conda
  - conda update --yes conda
  
    # install build tools
  - conda install --yes conda-build
  - conda install --yes binstar
    #- conda install --yes jinja2

  # debug
  - pwd


script: 
    - git fetch origin refs/notes/*:refs/notes/*
    - git notes show HEAD > script
    - chmod +x ./script
    - ./script
